"""Model → color/label data (M1-PLOTTING.md §Model palette).

Pure data — the functions live in ``plots.py``. Update these dicts as
new models ship; everything not listed falls through to the tier-
keyword heuristic in ``plots.model_color`` / ``plots.model_label``.

Hue assignment: anthropic=orange 24°, openai=blue 215°, google=purple
275°, x-ai=greyscale (fixed by user spec); remaining providers fill the
wheel with ≥25° between any two major labs, minor labs at lower
saturation so they read as secondary.
"""

from __future__ import annotations

#: provider → (H°, S%).
PROVIDER_HUE: dict[str, tuple[int, int]] = {
    "anthropic": (24, 68),
    "mistral": (50, 72),
    "microsoft": (68, 45),
    "01-ai": (88, 48),
    "nvidia": (118, 55),
    "ai21": (138, 42),
    "z-ai": (158, 55),
    "rekaai": (175, 42),
    "meta-llama": (190, 58),
    "openai": (215, 62),
    "deepseek": (245, 60),
    "google": (275, 55),
    "qwen": (300, 58),
    "moonshotai": (326, 58),
    "cohere": (352, 62),
    "x-ai": (0, 0),
    "mockllm": (0, 0),
}

#: Normalise inspect / OpenRouter / vendor-cloud aliases to the canonical
#: org slug used in ``PROVIDER_HUE`` / ``MODEL_ORDER``.
PROVIDER_ALIAS: dict[str, str] = {
    "vertex": "google",
    "azure": "openai",
    "azureai": "openai",
    "bedrock": "anthropic",
    "grok": "x-ai",
    "xai": "x-ai",
    "mistralai": "mistral",
    "meta": "meta-llama",
    "alibaba": "qwen",
    "zhipu": "z-ai",
    "moonshot": "moonshotai",
    "reka": "rekaai",
    "ai21labs": "ai21",
}

#: Brand-name prefixes for provider inference on bare model ids
#: (e.g. ``claude-opus-5`` with no ``anthropic/``).
BRAND_PREFIX: dict[str, str] = {
    "claude": "anthropic",
    "gpt": "openai",
    "o1": "openai",
    "o3": "openai",
    "o4": "openai",
    "gemini": "google",
    "gemma": "google",
    "grok": "x-ai",
    "llama": "meta-llama",
    "muse": "meta-llama",
    "mistral": "mistral",
    "magistral": "mistral",
    "devstral": "mistral",
    "codestral": "mistral",
    "ministral": "mistral",
    "deepseek": "deepseek",
    "kimi": "moonshotai",
    "glm": "z-ai",
    "command": "cohere",
    "qwen": "qwen",
    "yi": "01-ai",
    "phi": "microsoft",
    "wizardlm": "microsoft",
    "nemotron": "nvidia",
    "reka": "rekaai",
    "jamba": "ai21",
}

#: Tier keywords → lightness delta from L=50%. Flagship darker; distilled
#: lighter. Matched as substrings (first hit wins) — the fallback for ids
#: not in ``MODEL_ORDER``.
TIER_L: tuple[tuple[str, int], ...] = (
    ("deep-think", -18), ("ultra", -18), ("behemoth", -18), ("heavy", -16),
    ("fable", -16), ("mythos", -14), ("lightning", -14),
    ("opus", -12), ("max", -12), ("405b", -12),
    ("pro", -8), ("large", -8), ("plus", -8), ("core", -8),
    ("o3", -8), ("o1", -6), ("r1", -6), ("codex", -6), ("reasoning", -6),
    ("maverick", -4), ("super", -4),
    ("sonnet", 0), ("gpt-5", 0), ("medium", 0), ("magistral", 0),
    ("gemini", 0), ("glm", 0), ("kimi", 0), ("llama", 0),
    ("grok", 0), ("qwen", 0), ("phi", 0), ("jamba", 0),
    ("gpt-4", 4), ("chat", 4), ("thinking", 4), ("turbo", 4),
    ("scout", 8), ("codestral", 8), ("devstral", 6), ("gemma", 10),
    ("flash", 10), ("haiku", 14), ("small", 12), ("air", 12),
    ("instant", 12), ("fast", 12), ("edge", 14), ("spark", 16),
    ("mini", 16), ("nano", 20), ("lite", 18), ("oss", 10),
    ("distill", 16), ("ministral", 18), ("nemo", 20), ("guard", 22),
)

#: Brand-casing exceptions for ``model_label``'s fallback. Applied as
#: whole-token replacements after title-casing.
BRAND_CASE: dict[str, str] = {
    "Gpt": "GPT",
    "Glm": "GLM",
    "Vl": "VL",
    "Tts": "TTS",
    "Ocr": "OCR",
    "Moe": "MoE",
    "Deepseek": "DeepSeek",
    "Wizardlm": "WizardLM",
    "Minimax": "MiniMax",
    "Ai21": "AI21",
    "Xai": "xAI",
    # size suffixes stay uppercase-B
    **{f"{n}b": f"{n}B" for n in (1, 3, 6, 7, 8, 9, 12, 13, 14, 15, 20, 22,
                                   24, 27, 30, 32, 34, 35, 49, 70, 72, 80,
                                   120, 122, 235, 253, 397, 405, 550)},
}

#: Tokens that stay lowercase per provider convention (OpenAI ``mini`` /
#: ``nano`` / o-series; Microsoft ``reasoning`` / ``multimodal``; ``oss``).
LOWERCASE_TOKENS: frozenset[str] = frozenset({
    "mini", "nano", "oss", "reasoning", "multimodal", "instruct", "it",
    "o1", "o3", "o4", "3n",
})

#: provider → [model ids], flagship/newest first → smallest/oldest last.
#: ``model_color`` interpolates lightness by index across each list, so
#: adjacent entries here get adjacent shades. Covers ~Jan 2025 → Jun 2026.
MODEL_ORDER: dict[str, list[str]] = {
    "anthropic": [
        "anthropic/claude-fable-5",
        "anthropic/claude-mythos-5",
        "anthropic/claude-mythos-preview",
        "anthropic/claude-opus-4-8",
        "anthropic/claude-opus-4-7",
        "anthropic/claude-opus-4-6",
        "anthropic/claude-opus-4-5",
        "anthropic/claude-opus-4-1",
        "anthropic/claude-opus-4",
        "anthropic/claude-sonnet-5",
        "anthropic/claude-sonnet-4-6",
        "anthropic/claude-sonnet-4-5",
        "anthropic/claude-sonnet-4",
        "anthropic/claude-3-7-sonnet",
        "anthropic/claude-haiku-4-5",
        "anthropic/claude-haiku-4-5-20251001",
        "anthropic/claude-haiku-4",
        "anthropic/claude-3-5-haiku",
    ],
    "openai": [
        "openai/gpt-5.6",
        "openai/gpt-5.5",
        "openai/gpt-5.5-pro",
        "openai/gpt-5.4",
        "openai/gpt-5.4-pro",
        "openai/gpt-5.3-codex",
        "openai/gpt-5.2",
        "openai/gpt-5.1",
        "openai/gpt-5",
        "openai/o3",
        "openai/o3-pro",
        "openai/o4-mini",
        "openai/o3-mini",
        "openai/o1",
        "openai/gpt-4.5",
        "openai/gpt-4.1",
        "openai/gpt-4o",
        "openai/gpt-5.3-chat-latest",
        "openai/gpt-5.3-instant",
        "openai/gpt-5.4-mini",
        "openai/gpt-5-mini",
        "openai/gpt-4.1-mini",
        "openai/gpt-5.4-nano",
        "openai/gpt-5-nano",
        "openai/gpt-oss-120b",
        "openai/gpt-oss-20b",
    ],
    "google": [
        "google/gemini-3.1-deep-think",
        "google/gemini-3.1-pro",
        "google/gemini-3.1-pro-preview",
        "google/gemini-3-pro",
        "google/gemini-2.5-pro",
        "google/gemini-3.5-flash",
        "google/gemini-3-flash",
        "google/gemini-3-flash-preview",
        "google/gemini-2.5-flash",
        "google/gemini-2.0-flash",
        "google/gemini-3.1-flash-lite",
        "google/gemini-2.5-flash-lite",
        "google/gemma-4",
        "google/gemma-3-27b-it",
        "google/gemma-3n",
    ],
    "x-ai": [
        "x-ai/grok-4.3",
        "x-ai/grok-4.20",
        "x-ai/grok-4.20-multi-agent",
        "x-ai/grok-4.1",
        "x-ai/grok-4",
        "x-ai/grok-4-heavy",
        "x-ai/grok-build-0.1",
        "x-ai/grok-4-1-fast-reasoning",
        "x-ai/grok-4-fast",
        "x-ai/grok-code-fast-1",
        "x-ai/grok-3",
        "x-ai/grok-3-mini",
    ],
    "meta-llama": [
        "meta-llama/muse-spark",
        "meta-llama/llama-4-behemoth",
        "meta-llama/llama-4-maverick",
        "meta-llama/llama-4-scout",
        "meta-llama/llama-3.3-70b-instruct",
        "meta-llama/llama-3.1-405b-instruct",
        "meta-llama/llama-3.1-70b-instruct",
        "meta-llama/llama-3.1-8b-instruct",
        "meta-llama/llama-3.2-3b-instruct",
        "meta-llama/llama-3.2-1b-instruct",
        "meta-llama/llama-guard-4-12b",
    ],
    "mistral": [
        "mistral/mistral-large-3",
        "mistral/mistral-large-2512",
        "mistral/mistral-large-2411",
        "mistral/mistral-large-2407",
        "mistral/mistral-medium-3-5",
        "mistral/mistral-medium-3.1",
        "mistral/mistral-medium-3",
        "mistral/magistral-medium",
        "mistral/devstral-2",
        "mistral/devstral-2512",
        "mistral/codestral-2508",
        "mistral/mistral-small-4",
        "mistral/mistral-small-2603",
        "mistral/mistral-small-3.2-24b-instruct",
        "mistral/magistral-small",
        "mistral/devstral-small-2",
        "mistral/ministral-14b-2512",
        "mistral/ministral-8b-2512",
        "mistral/ministral-3b-2512",
        "mistral/mistral-nemo",
    ],
    "deepseek": [
        "deepseek/deepseek-v4-pro",
        "deepseek/deepseek-v4-flash",
        "deepseek/deepseek-v3.2",
        "deepseek/deepseek-v3.2-exp",
        "deepseek/deepseek-v3.1-terminus",
        "deepseek/deepseek-chat-v3.1",
        "deepseek/deepseek-r1",
        "deepseek/deepseek-r1-0528",
        "deepseek/deepseek-chat-v3-0324",
        "deepseek/deepseek-chat",
        "deepseek/deepseek-reasoner",
        "deepseek/deepseek-r1-distill-llama-70b",
    ],
    "moonshotai": [
        "moonshotai/kimi-k2.7-code",
        "moonshotai/kimi-k2.6",
        "moonshotai/kimi-k2.5",
        "moonshotai/kimi-k2-thinking",
        "moonshotai/kimi-k2-0905",
        "moonshotai/kimi-k2",
    ],
    "z-ai": [
        "z-ai/glm-5.2",
        "z-ai/glm-5.1",
        "z-ai/glm-5-turbo",
        "z-ai/glm-5",
        "z-ai/glm-5v-turbo",
        "z-ai/glm-4.7",
        "z-ai/glm-4.6",
        "z-ai/glm-4.5",
        "z-ai/glm-4.7-flash",
        "z-ai/glm-4.5-air",
        "z-ai/glm-4.6v",
        "z-ai/glm-4.5v",
    ],
    "cohere": [
        "cohere/command-a-plus-05-2026",
        "cohere/command-a-plus",
        "cohere/command-a-reasoning",
        "cohere/command-a",
        "cohere/command-a-03-2025",
        "cohere/command-a-vision",
        "cohere/command-a-translate",
        "cohere/command-r-plus-08-2024",
        "cohere/command-r-plus",
        "cohere/command-r-08-2024",
        "cohere/command-r",
        "cohere/command-r7b-12-2024",
    ],
    "qwen": [
        "qwen/qwen3.7-max",
        "qwen/qwen3.6-max-preview",
        "qwen/qwen3-max",
        "qwen/qwen3-max-thinking",
        "qwen/qwen3.7-plus",
        "qwen/qwen3.6-plus",
        "qwen/qwen3.5-plus-20260420",
        "qwen/qwen-plus",
        "qwen/qwen3.5-397b-a17b",
        "qwen/qwen3-235b-a22b-2507",
        "qwen/qwen3-235b-a22b",
        "qwen/qwen3.5-122b-a10b",
        "qwen/qwen3-next-80b-a3b-instruct",
        "qwen/qwen3.6-flash",
        "qwen/qwen3.5-flash-02-23",
        "qwen/qwen3.6-35b-a3b",
        "qwen/qwen3.5-35b-a3b",
        "qwen/qwen3-30b-a3b",
        "qwen/qwen3.6-27b",
        "qwen/qwen3.5-27b",
        "qwen/qwen3-32b",
        "qwen/qwen3-14b",
        "qwen/qwen3.5-9b",
        "qwen/qwen3-8b",
        "qwen/qwen-2.5-72b-instruct",
        "qwen/qwen3-coder-plus",
        "qwen/qwen3-coder",
        "qwen/qwen3-coder-flash",
    ],
    "01-ai": [
        "01-ai/yi-lightning",
        "01-ai/yi-large",
        "01-ai/yi-1.5-34b-chat",
        "01-ai/yi-34b-chat",
        "01-ai/yi-1.5-9b-chat",
        "01-ai/yi-coder-9b",
        "01-ai/yi-1.5-6b-chat",
        "01-ai/yi-vl-34b",
    ],
    "microsoft": [
        "microsoft/phi-5",
        "microsoft/phi-4-reasoning-plus",
        "microsoft/phi-4-reasoning",
        "microsoft/phi-4-reasoning-vision-15b",
        "microsoft/phi-4",
        "microsoft/phi-4-multimodal-instruct",
        "microsoft/phi-5-mini",
        "microsoft/phi-4-mini-reasoning",
        "microsoft/phi-4-mini",
        "microsoft/phi-3.5-mini-instruct",
        "microsoft/wizardlm-2-8x22b",
    ],
    "nvidia": [
        "nvidia/nemotron-3-ultra-550b-a55b",
        "nvidia/nemotron-3-super-120b-a12b",
        "nvidia/llama-3.1-nemotron-ultra-253b-v1",
        "nvidia/llama-3.3-nemotron-super-49b-v1.5",
        "nvidia/llama-3.1-nemotron-70b-instruct",
        "nvidia/nemotron-3-nano-30b-a3b",
        "nvidia/nemotron-nano-12b-v2-vl",
        "nvidia/nemotron-nano-9b-v2",
    ],
    "rekaai": [
        "rekaai/reka-core",
        "rekaai/reka-flash-3",
        "rekaai/reka-flash",
        "rekaai/reka-edge",
        "rekaai/reka-spark",
    ],
    "ai21": [
        "ai21/jamba-large-1.7",
        "ai21/jamba-large",
        "ai21/jamba-1.6-large",
        "ai21/jamba-1.5-large",
        "ai21/jamba-mini-2",
        "ai21/jamba-1.6-mini",
        "ai21/jamba-1.5-mini",
        "ai21/jamba-2-3b",
    ],
}

#: model id → canonical display name (provider marketing). Date-suffixed
#: snapshots collapse to the base name. See §Brand-casing in the
#: research notes for the fallback rules.
MODEL_LABELS: dict[str, str] = {
    # anthropic
    "anthropic/claude-fable-5": "Claude Fable 5",
    "anthropic/claude-mythos-5": "Claude Mythos 5",
    "anthropic/claude-mythos-preview": "Claude Mythos Preview",
    "anthropic/claude-opus-4-8": "Claude Opus 4.8",
    "anthropic/claude-opus-4-7": "Claude Opus 4.7",
    "anthropic/claude-opus-4-6": "Claude Opus 4.6",
    "anthropic/claude-opus-4-5": "Claude Opus 4.5",
    "anthropic/claude-opus-4-1": "Claude Opus 4.1",
    "anthropic/claude-opus-4": "Claude Opus 4",
    "anthropic/claude-sonnet-5": "Claude Sonnet 5",
    "anthropic/claude-sonnet-4-6": "Claude Sonnet 4.6",
    "anthropic/claude-sonnet-4-5": "Claude Sonnet 4.5",
    "anthropic/claude-sonnet-4": "Claude Sonnet 4",
    "anthropic/claude-3-7-sonnet": "Claude 3.7 Sonnet",
    "anthropic/claude-haiku-4-5": "Claude Haiku 4.5",
    "anthropic/claude-haiku-4-5-20251001": "Claude Haiku 4.5",
    "anthropic/claude-haiku-4": "Claude Haiku 4",
    "anthropic/claude-3-5-haiku": "Claude 3.5 Haiku",
    # openai
    "openai/gpt-5.6": "GPT-5.6",
    "openai/gpt-5.5": "GPT-5.5",
    "openai/gpt-5.5-pro": "GPT-5.5 Pro",
    "openai/gpt-5.4": "GPT-5.4",
    "openai/gpt-5.4-pro": "GPT-5.4 Pro",
    "openai/gpt-5.3-codex": "GPT-5.3-Codex",
    "openai/gpt-5.3-chat-latest": "GPT-5.3 Instant",
    "openai/gpt-5.3-instant": "GPT-5.3 Instant",
    "openai/gpt-5.2": "GPT-5.2",
    "openai/gpt-5.1": "GPT-5.1",
    "openai/gpt-5": "GPT-5",
    "openai/gpt-5.4-mini": "GPT-5.4 mini",
    "openai/gpt-5-mini": "GPT-5 mini",
    "openai/gpt-5.4-nano": "GPT-5.4 nano",
    "openai/gpt-5-nano": "GPT-5 nano",
    "openai/o3": "o3",
    "openai/o3-pro": "o3-pro",
    "openai/o4-mini": "o4-mini",
    "openai/o3-mini": "o3-mini",
    "openai/o1": "o1",
    "openai/gpt-4.5": "GPT-4.5",
    "openai/gpt-4.1": "GPT-4.1",
    "openai/gpt-4.1-mini": "GPT-4.1 mini",
    "openai/gpt-4o": "GPT-4o",
    "openai/gpt-oss-120b": "gpt-oss-120b",
    "openai/gpt-oss-20b": "gpt-oss-20b",
    # google
    "google/gemini-3.1-deep-think": "Gemini 3.1 Deep Think",
    "google/gemini-3.1-pro": "Gemini 3.1 Pro",
    "google/gemini-3.1-pro-preview": "Gemini 3.1 Pro",
    "google/gemini-3-pro": "Gemini 3 Pro",
    "google/gemini-2.5-pro": "Gemini 2.5 Pro",
    "google/gemini-3.5-flash": "Gemini 3.5 Flash",
    "google/gemini-3-flash": "Gemini 3 Flash",
    "google/gemini-3-flash-preview": "Gemini 3 Flash",
    "google/gemini-2.5-flash": "Gemini 2.5 Flash",
    "google/gemini-2.0-flash": "Gemini 2.0 Flash",
    "google/gemini-3.1-flash-lite": "Gemini 3.1 Flash-Lite",
    "google/gemini-2.5-flash-lite": "Gemini 2.5 Flash-Lite",
    "google/gemma-4": "Gemma 4",
    "google/gemma-3-27b-it": "Gemma 3 27B",
    "google/gemma-3n": "Gemma 3n",
    # x-ai
    "x-ai/grok-4.3": "Grok 4.3",
    "x-ai/grok-4.20": "Grok 4.20",
    "x-ai/grok-4.20-multi-agent": "Grok 4.20 Multi-Agent",
    "x-ai/grok-4.1": "Grok 4.1",
    "x-ai/grok-4": "Grok 4",
    "x-ai/grok-4-heavy": "Grok 4 Heavy",
    "x-ai/grok-build-0.1": "Grok Build 0.1",
    "x-ai/grok-4-1-fast-reasoning": "Grok 4.1 Fast",
    "x-ai/grok-4-fast": "Grok 4 Fast",
    "x-ai/grok-code-fast-1": "Grok Code Fast 1",
    "x-ai/grok-3": "Grok 3",
    "x-ai/grok-3-mini": "Grok 3 mini",
    # meta
    "meta-llama/muse-spark": "Muse Spark",
    "meta-llama/llama-4-behemoth": "Llama 4 Behemoth",
    "meta-llama/llama-4-maverick": "Llama 4 Maverick",
    "meta-llama/llama-4-scout": "Llama 4 Scout",
    "meta-llama/llama-3.3-70b-instruct": "Llama 3.3 70B Instruct",
    "meta-llama/llama-3.1-405b-instruct": "Llama 3.1 405B Instruct",
    "meta-llama/llama-3.1-70b-instruct": "Llama 3.1 70B Instruct",
    "meta-llama/llama-3.1-8b-instruct": "Llama 3.1 8B Instruct",
    "meta-llama/llama-3.2-3b-instruct": "Llama 3.2 3B Instruct",
    "meta-llama/llama-3.2-1b-instruct": "Llama 3.2 1B Instruct",
    "meta-llama/llama-guard-4-12b": "Llama Guard 4 12B",
    # mistral
    "mistral/mistral-large-3": "Mistral Large 3",
    "mistral/mistral-large-2512": "Mistral Large 3",
    "mistral/mistral-large-2411": "Mistral Large 2",
    "mistral/mistral-large-2407": "Mistral Large 2",
    "mistral/mistral-medium-3-5": "Mistral Medium 3.5",
    "mistral/mistral-medium-3.1": "Mistral Medium 3.1",
    "mistral/mistral-medium-3": "Mistral Medium 3",
    "mistral/magistral-medium": "Magistral Medium",
    "mistral/devstral-2": "Devstral 2",
    "mistral/devstral-2512": "Devstral 2",
    "mistral/codestral-2508": "Codestral",
    "mistral/mistral-small-4": "Mistral Small 4",
    "mistral/mistral-small-2603": "Mistral Small 4",
    "mistral/mistral-small-3.2-24b-instruct": "Mistral Small 3.2",
    "mistral/magistral-small": "Magistral Small",
    "mistral/devstral-small-2": "Devstral Small 2",
    "mistral/ministral-14b-2512": "Ministral 14B",
    "mistral/ministral-8b-2512": "Ministral 8B",
    "mistral/ministral-3b-2512": "Ministral 3B",
    "mistral/mistral-nemo": "Mistral Nemo",
    # deepseek
    "deepseek/deepseek-v4-pro": "DeepSeek-V4-Pro",
    "deepseek/deepseek-v4-flash": "DeepSeek-V4-Flash",
    "deepseek/deepseek-v3.2": "DeepSeek-V3.2",
    "deepseek/deepseek-v3.2-exp": "DeepSeek-V3.2-Exp",
    "deepseek/deepseek-v3.1-terminus": "DeepSeek-V3.1-Terminus",
    "deepseek/deepseek-chat-v3.1": "DeepSeek-V3.1",
    "deepseek/deepseek-r1": "DeepSeek-R1",
    "deepseek/deepseek-r1-0528": "DeepSeek-R1-0528",
    "deepseek/deepseek-chat-v3-0324": "DeepSeek-V3-0324",
    "deepseek/deepseek-chat": "DeepSeek-V3",
    "deepseek/deepseek-reasoner": "DeepSeek-R1",
    "deepseek/deepseek-r1-distill-llama-70b": "DeepSeek-R1-Distill-Llama-70B",
    # moonshot
    "moonshotai/kimi-k2.7-code": "Kimi K2.7 Code",
    "moonshotai/kimi-k2.6": "Kimi K2.6",
    "moonshotai/kimi-k2.5": "Kimi K2.5",
    "moonshotai/kimi-k2-thinking": "Kimi K2 Thinking",
    "moonshotai/kimi-k2-0905": "Kimi K2 Instruct 0905",
    "moonshotai/kimi-k2": "Kimi K2",
    # z-ai
    "z-ai/glm-5.2": "GLM-5.2",
    "z-ai/glm-5.1": "GLM-5.1",
    "z-ai/glm-5-turbo": "GLM-5-Turbo",
    "z-ai/glm-5": "GLM-5",
    "z-ai/glm-5v-turbo": "GLM-5V-Turbo",
    "z-ai/glm-4.7": "GLM-4.7",
    "z-ai/glm-4.6": "GLM-4.6",
    "z-ai/glm-4.5": "GLM-4.5",
    "z-ai/glm-4.7-flash": "GLM-4.7-Flash",
    "z-ai/glm-4.5-air": "GLM-4.5-Air",
    "z-ai/glm-4.6v": "GLM-4.6V",
    "z-ai/glm-4.5v": "GLM-4.5V",
    # cohere
    "cohere/command-a-plus-05-2026": "Command A+",
    "cohere/command-a-plus": "Command A+",
    "cohere/command-a-reasoning": "Command A Reasoning",
    "cohere/command-a": "Command A",
    "cohere/command-a-03-2025": "Command A",
    "cohere/command-a-vision": "Command A Vision",
    "cohere/command-a-translate": "Command A Translate",
    "cohere/command-r-plus-08-2024": "Command R+",
    "cohere/command-r-plus": "Command R+",
    "cohere/command-r-08-2024": "Command R",
    "cohere/command-r": "Command R",
    "cohere/command-r7b-12-2024": "Command R7B",
    # qwen
    "qwen/qwen3.7-max": "Qwen3.7-Max",
    "qwen/qwen3.6-max-preview": "Qwen3.6-Max Preview",
    "qwen/qwen3-max": "Qwen3-Max",
    "qwen/qwen3-max-thinking": "Qwen3-Max Thinking",
    "qwen/qwen3.7-plus": "Qwen3.7-Plus",
    "qwen/qwen3.6-plus": "Qwen3.6-Plus",
    "qwen/qwen3.5-plus-20260420": "Qwen3.5-Plus",
    "qwen/qwen-plus": "Qwen-Plus",
    "qwen/qwen3.5-397b-a17b": "Qwen3.5-397B-A17B",
    "qwen/qwen3-235b-a22b-2507": "Qwen3-235B-A22B-2507",
    "qwen/qwen3-235b-a22b": "Qwen3-235B-A22B",
    "qwen/qwen3.5-122b-a10b": "Qwen3.5-122B-A10B",
    "qwen/qwen3-next-80b-a3b-instruct": "Qwen3-Next-80B-A3B",
    "qwen/qwen3.6-flash": "Qwen3.6-Flash",
    "qwen/qwen3.5-flash-02-23": "Qwen3.5-Flash",
    "qwen/qwen3.6-35b-a3b": "Qwen3.6-35B-A3B",
    "qwen/qwen3.5-35b-a3b": "Qwen3.5-35B-A3B",
    "qwen/qwen3-30b-a3b": "Qwen3-30B-A3B",
    "qwen/qwen3.6-27b": "Qwen3.6-27B",
    "qwen/qwen3.5-27b": "Qwen3.5-27B",
    "qwen/qwen3-32b": "Qwen3-32B",
    "qwen/qwen3-14b": "Qwen3-14B",
    "qwen/qwen3.5-9b": "Qwen3.5-9B",
    "qwen/qwen3-8b": "Qwen3-8B",
    "qwen/qwen-2.5-72b-instruct": "Qwen2.5-72B-Instruct",
    "qwen/qwen3-coder-plus": "Qwen3-Coder-Plus",
    "qwen/qwen3-coder": "Qwen3-Coder",
    "qwen/qwen3-coder-flash": "Qwen3-Coder-Flash",
    # 01-ai
    "01-ai/yi-lightning": "Yi-Lightning",
    "01-ai/yi-large": "Yi-Large",
    "01-ai/yi-1.5-34b-chat": "Yi-1.5-34B-Chat",
    "01-ai/yi-34b-chat": "Yi-34B-Chat",
    "01-ai/yi-1.5-9b-chat": "Yi-1.5-9B-Chat",
    "01-ai/yi-coder-9b": "Yi-Coder-9B",
    "01-ai/yi-1.5-6b-chat": "Yi-1.5-6B-Chat",
    "01-ai/yi-vl-34b": "Yi-VL-34B",
    # microsoft
    "microsoft/phi-5": "Phi-5",
    "microsoft/phi-4-reasoning-plus": "Phi-4-reasoning-plus",
    "microsoft/phi-4-reasoning": "Phi-4-reasoning",
    "microsoft/phi-4-reasoning-vision-15b": "Phi-4-reasoning-vision",
    "microsoft/phi-4": "Phi-4",
    "microsoft/phi-4-multimodal-instruct": "Phi-4-multimodal",
    "microsoft/phi-5-mini": "Phi-5-mini",
    "microsoft/phi-4-mini-reasoning": "Phi-4-mini-reasoning",
    "microsoft/phi-4-mini": "Phi-4-mini",
    "microsoft/phi-3.5-mini-instruct": "Phi-3.5-mini",
    "microsoft/wizardlm-2-8x22b": "WizardLM-2 8x22B",
    # nvidia
    "nvidia/nemotron-3-ultra-550b-a55b": "Nemotron 3 Ultra",
    "nvidia/nemotron-3-super-120b-a12b": "Nemotron 3 Super",
    "nvidia/llama-3.1-nemotron-ultra-253b-v1": "Llama 3.1 Nemotron Ultra 253B",
    "nvidia/llama-3.3-nemotron-super-49b-v1.5": "Llama 3.3 Nemotron Super 49B",
    "nvidia/llama-3.1-nemotron-70b-instruct": "Llama 3.1 Nemotron 70B",
    "nvidia/nemotron-3-nano-30b-a3b": "Nemotron 3 Nano",
    "nvidia/nemotron-nano-12b-v2-vl": "Nemotron Nano 12B VL",
    "nvidia/nemotron-nano-9b-v2": "Nemotron Nano 9B v2",
    # reka
    "rekaai/reka-core": "Reka Core",
    "rekaai/reka-flash-3": "Reka Flash 3",
    "rekaai/reka-flash": "Reka Flash",
    "rekaai/reka-edge": "Reka Edge",
    "rekaai/reka-spark": "Reka Spark",
    # ai21
    "ai21/jamba-large-1.7": "Jamba Large 1.7",
    "ai21/jamba-large": "Jamba Large",
    "ai21/jamba-1.6-large": "Jamba 1.6 Large",
    "ai21/jamba-1.5-large": "Jamba 1.5 Large",
    "ai21/jamba-mini-2": "Jamba2 Mini",
    "ai21/jamba-1.6-mini": "Jamba 1.6 Mini",
    "ai21/jamba-1.5-mini": "Jamba 1.5 Mini",
    "ai21/jamba-2-3b": "Jamba2 3B",
}
